# flake8:noqa:E704
"""modint stub file for c-extension
"""

class ModInt:
    def __init__(self, value: int = 0) -> None: ...
    def __add__(self, rhs: int | "ModInt") -> "ModInt": ...
    def __iadd__(self, rhs: int | "ModInt") -> "ModInt": ...
    @property
    def value(self) -> int: ...
    @classmethod
    def mod(cls) -> int: ...
    @classmethod
    def set_mod(cls, mod: int) -> None: ...
